name: Release

on:
  # Manual trigger from the Github Actions tab
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUBSERVICETOKEN }}
  COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

jobs:
  release-adapter:
    runs-on: macos-latest
    steps:
      - uses: chartboost/chartboost-mediation-ios-actions/release-adapter@v1
        with:
          allow-warnings: true
