name: Smoke Test

on:
  # On pull requests to main
  pull_request:
    branches:
      - main
  # Manual trigger from the Github Actions tab
  workflow_dispatch:

jobs:
  validate-podspec:
    runs-on: macos-latest
    steps:
      - uses: chartboost/chartboost-mediation-ios-actions/adapter-smoke-test@v1
        with:
          allow-warnings: true
