name: Smoke Test

on:
  # On pull requests to main
  pull_request:
    branches:
      - main
  # Manual trigger from the Github Actions tab
  workflow_dispatch:

jobs:
  validate-podspec:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: '15.3' # Google Mobile Ads SDK requires Xcode 15.3 starting in version 11.6.0

      - uses: chartboost/chartboost-mediation-ios-actions/adapter-smoke-test@v1
        with:
          allow-warnings: true
